# Create references for values that will be used
# repeatedly throughout the config
anchors:
- &cargo cargo
- &example-process ~/dev/multi-host/example-process/
- &args ["run", "-q", "--", "--forever"]

# Processes to host
process:
- name: process A
  exe: *cargo
  cwd: *example-process
  args: *args
  auto_start: true
- name: process B
  exe: *cargo
  cwd: *example-process
  args: *args
  auto_start: true
- name: process C
  exe: *cargo
  cwd: *example-process
  args: *args
  auto_start: true
